- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible #If the variable is COURSE=Ansible, we can refer to its value using $COURSE or ${COURSE} both are valid.
    DURATION: 10HR
    TRAINER: Shiva
  tasks:
  - name: print course information
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print Course information again
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"
      