- name: variables from file
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
  - name: print cpurse information
    ansible. builtin.debug:
      msg: "Hello I am Learning {{ Course }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"