- name: variables from inventory
  hosts: local
  Connection: local
  tasks:
  - name: Print Course Information
    ansible.builtin.debug:
      msg: "Hello I'm Learning: {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"